version: "3.9"
services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - DATABASE_URL=sqlite:///./data/rollodex.db
  db:
    image: nouchka/sqlite3
    volumes:
      - ./data:/root/db
    tty: true
